.open lfi.db

CREATE TABLE IF NOT EXISTS URL_TO_NUMER (CLURL VARCHAR (512) NOT NULL, ITIME BIGINT UNSIGNED NOT NULL, IRANK INTEGER PRIMARY KEY AUTOINCREMENT, IKIND INT NOT NULL, UNIQUE (CLURL));

CREATE TABLE IF NOT EXISTS LFI_PURE (IRANK INTEGER NOT NULL, CLNOMA CHAR (16) NOT NULL, IPOSEX BIGINT NOT NULL, 
                                     ILONGD BIGINT NOT NULL, KDATA BLOB, UNIQUE (IRANK, CLNOMA));

CREATE TABLE IF NOT EXISTS LFI_MULT (IRANK INTEGER NOT NULL, CLNOMA CHAR (16) NOT NULL, CLNOMB CHAR (16) NOT NULL, JRANK INTEGER NOT NULL, UNIQUE (IRANK, CLNOMA));



