.open lfi.db

CREATE TABLE URL_TO_NUMER (URL VARCHAR (512) NOT NULL, TIME BIGINT UNSIGNED NOT NULL, IRANK INTEGER PRIMARY KEY AUTOINCREMENT, UNIQUE (URL));

CREATE TABLE LFI_PURE_INDEX (IRANK INTEGER NOT NULL, CLNOMA CHAR (16) NOT NULL, IPOSEX INTEGER NOT NULL, 
                             ILONGD INTEGER NOT NULL, UNIQUE (IRANK, CLNOMA));



