.open lfi.db

CREATE TABLE URL_TO_NUMER (URL VARCHAR (512) NOT NULL, TIME BIGINT UNSIGNED NOT NULL, IRANK INTEGER PRIMARY KEY AUTOINCREMENT, KIND INT NOT NULL, UNIQUE (URL));

CREATE TABLE LFI_PURE (IRANK INTEGER NOT NULL, CLNOMA CHAR (16) NOT NULL, IPOSEX BIGINT NOT NULL, 
                       ILONGD BIGINT NOT NULL, DATA BLOB, UNIQUE (IRANK, CLNOMA));

CREATE TABLE LFI_MULT (IRANK INTEGER NOT NULL, CLNOMA CHAR (16) NOT NULL, CLNOMB CHAR (16) NOT NULL, JRANK INTEGER NOT NULL, UNIQUE (IRANK, CLNOMA));



