all: 
	cd LFI && make all -j4
	cd glGrib && make all -j4
	cd perl/glfw && make
	cd glGribTk && make

clean:
	cd LFI && make clean
	cd glGrib && make clean
	cd perl/glfw && make clean
	cd glGribTk && make clean
