all: 
	cd LFI && make all -j4
	cd glGrib && make all -j4
	cd perl/glfw && make
	cd python2 && make
	cd python3 && make

clean:
	cd LFI && make clean
	cd glGrib && make clean
	cd perl/glfw && make clean
